# Generated by Django 2.1.1 on 2019-11-26 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='sns.Sns', verbose_name='인스타그램'),
        ),
    ]
