# Generated by Django 2.1.13 on 2019-11-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='timeline_photo/%Y/%m/%d', verbose_name='사진')),
                ('instagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='인스타그램')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sns',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Sns',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='like',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1, max_length=100, verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='instagram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='인스타그램'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sns',
            name='content',
            field=models.TextField(default=1, max_length=100, verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='sns',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
