# Generated by Django 2.1.13 on 2019-11-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns', '0002_auto_20191111_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snsphoto',
            name='instagram',
        ),
        migrations.AlterModelOptions(
            name='sns',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='Sns',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sns',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sns',
            name='image',
            field=models.ImageField(default=1, upload_to='timeline_photo/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sns',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sns',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sns',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SnsPhoto',
        ),
    ]
