# Generated by Django 2.1.13 on 2019-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20191111_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Sns',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sns',
            name='update',
        ),
        migrations.AddField(
            model_name='sns',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sns',
            name='image',
            field=models.ImageField(upload_to='timeline_sns/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
