# Generated by Django 2.1.13 on 2019-11-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_auto_20191112_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sns',
            old_name='updated',
            new_name='update',
        ),
    ]
