# Generated by Django 2.1.13 on 2019-11-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_auto_20191116_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='instagram',
            new_name='sns',
        ),
    ]
