# Generated by Django 2.1.13 on 2019-11-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0007_auto_20191116_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sns',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
