# Generated by Django 2.1.5 on 2019-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
