# Generated by Django 2.1.1 on 2019-10-31 12:25

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=jsonfield.fields.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
