# Generated by Django 2.1.5 on 2019-11-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=100)),
                ('rgb_value', models.CharField(default='', max_length=100)),
                ('image_link', models.TextField(default='')),
                ('similar_cosmetics', jsonfield.fields.JSONField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic_Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', jsonfield.fields.JSONField(default='{"기초": {"스킨": 5, "로션": 5, "에센스": 5, "크림": 5, "미스트": 5, "메이크업픽서": 5, "페이스오일": 5, "토너/필링패드": 5}, "베이스": {"메이크업베이스": 5, "톤업크림": 5, "베이스프라이머": 5, "포인트프라이머": 5, "파운데이션": 5, "비비크림": 5, "씨씨크림": 5, "쿠션타입": 5, "컨실러": 5, "팩트": 5, "파우더": 5, "트윈케익": 5}, "색조": {"립스틱": 5, "립글로스/락커": 5, "립틴트": 5, "립밤": 5, "립라이너": 5, "아이라이너": 5, "마스카라": 5, "픽서/영양제": 5, "아이섀도우": 5, "아이브로우": 5, "하이라이터": 5, "쉐딩": 5, "블러셔": 5}}')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('image_link', models.CharField(default='', max_length=1000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Small_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_category', models.CharField(default='', max_length=100)),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Big_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(default='', max_length=100)),
                ('alarm_cycle', models.IntegerField(blank=True, default=0, null=True)),
                ('is_consent_alarm', models.BooleanField(default=True)),
                ('selected_similar_cosmetics', jsonfield.fields.JSONField(default='')),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Cosmetic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Interested_Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_similar_cosmetics', jsonfield.fields.JSONField(default='')),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Cosmetic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Small_Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_names',
            field=models.ManyToManyField(blank=True, to='cosmetic.Tag'),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Product'),
        ),
    ]
