# Generated by Django 2.1.13 on 2019-11-11 13:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_category', models.CharField(default='', max_length=100)),
                ('small_category', models.CharField(default='', max_length=100)),
                ('cosmetic_name', models.CharField(default='', max_length=30)),
                ('brand_name', models.CharField(default='', max_length=30)),
                ('image_link', models.CharField(default='', max_length=100)),
                ('option_names', jsonfield.fields.JSONField(default='')),
                ('tag_names', jsonfield.fields.JSONField(default='')),
            ],
        ),
    ]
