# Generated by Django 2.1.1 on 2019-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0002_auto_20191029_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='big_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='small_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
