# Generated by Django 2.1.1 on 2019-10-31 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosmetic', '0003_auto_20191029_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic_Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', jsonfield.fields.JSONField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('tag_contents', jsonfield.fields.JSONField(default='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Small_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_category', models.CharField(default='', max_length=100)),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Big_Category')),
            ],
        ),
        # migrations.CreateModel(
        #     name='User_Cosmetic',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('expiration_date', models.DateTimeField(default='', max_length=100)),
        #         ('is_consent_alarm', models.BooleanField(default=True)),
        #         ('selected_similar_cosmetics', jsonfield.fields.JSONField(default='')),
        #     ],
        # ),
        migrations.RenameField(
            model_name='cosmetic',
            old_name='big_category',
            new_name='rgb_value',
        ),
        migrations.RenameField(
            model_name='cosmetic',
            old_name='option_names',
            new_name='similar_cosmetics',
        ),
        migrations.RenameField(
            model_name='cosmetic',
            old_name='small_category',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='cosmetic_name',
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='tag_names',
        ),
        # migrations.AddField(
        #     model_name='user_cosmetic',
        #     name='cosmetic',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Cosmetic'),
        # ),
        # migrations.AddField(
        #     model_name='user_cosmetic',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Small_Category'),
        ),
        migrations.AddField(
            model_name='cosmetic_importance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Small_Category'),
        ),
        migrations.AddField(
            model_name='cosmetic_importance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Product'),
        ),
    ]
