# Generated by Django 2.1.1 on 2019-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0004_auto_20191031_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag_contents',
        ),
        migrations.AddField(
            model_name='product',
            name='tag_names',
            field=models.ManyToManyField(to='cosmetic.Tag'),
        ),
    ]
