# Generated by Django 2.1.1 on 2019-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0005_auto_20191031_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag_names',
            field=models.ManyToManyField(default='', to='cosmetic.Tag'),
        ),
    ]
