# Generated by Django 2.1.1 on 2019-11-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0008_auto_20191102_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
