# Generated by Django 2.1.1 on 2019-11-03 08:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0010_user_interested_cosmetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_interested_cosmetic',
            name='selected_similar_cosmetics',
            field=jsonfield.fields.JSONField(default=''),
        ),
    ]
