# Generated by Django 2.1.1 on 2019-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0011_user_interested_cosmetic_selected_similar_cosmetics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
