# Generated by Django 2.1.1 on 2019-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0012_auto_20191103_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='image_link',
            field=models.TextField(default=''),
        ),
    ]
