# Generated by Django 2.1.1 on 2019-11-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0013_auto_20191103_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to='cosmetic.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_names',
            field=models.ManyToManyField(blank=True, to='cosmetic.Tag'),
        ),
    ]
