# Generated by Django 2.1.1 on 2019-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0014_auto_20191104_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cosmetic',
            name='alarm_cycle',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
