# Generated by Django 2.1.1 on 2019-11-15 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cosmetic', '0014_auto_20191104_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(default='', max_length=100)),
                ('alarm_cycle', models.IntegerField(blank=True, default=0, null=True)),
                ('is_consent_alarm', models.BooleanField(default=True)),
                ('selected_similar_cosmetics', jsonfield.fields.JSONField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Product'),
        ),
        migrations.AddField(
            model_name='user_cosmetic',
            name='cosmetic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Cosmetic'),
        ),
        migrations.AddField(
            model_name='user_cosmetic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
