# Generated by Django 2.1.1 on 2019-11-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0015_user_cosmetic_alarm_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cosmetic.Product'),
        ),
    ]
