# Generated by Django 2.1.1 on 2019-11-19 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0015_auto_20191115_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetic_importance',
            name='category',
        ),
        migrations.AlterField(
            model_name='cosmetic_importance',
            name='importance',
            field=jsonfield.fields.JSONField(default={'로션': 10, '립글로스/락커': 10, '립라이너': 10, '립밤': 10, '립스틱': 10, '립틴트': 10, '마스카라': 10, '메이크업베이스:': 10, '메이크업픽서': 10, '미스트': 10, '베이스프라이머': 10, '블러셔': 10, '비비크림': 10, '쉐딩': 10, '스킨': 10, '씨씨크림': 10, '아이라이너': 10, '아이브로우': 10, '아이섀도우': 10, '에센스': 10, '컨실러': 10, '쿠션타입': 10, '크림': 10, '토너/필링패드': 10, '톤업크림': 10, '트윈케익': 10, '파우더': 10, '파운데이션': 10, '팩트': 10, '페이스오일': 10, '포인트프라이머': 10, '픽서/영양제': 10, '하이라이터': 10}),
        ),
        migrations.AlterField(
            model_name='cosmetic_importance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
